server:
  port: ${vcap.application.port:8761}

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0
